### ISSUE TITLE
Traceback on malformed rst

### ISSUE THREAD

**Issue by valholl** [rst2pdf/rst2pdf#550] opened 2015-08-26 17:46 UTC
As reported on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=639544 when using rst2pdf on malformed rst that causes a docutils.utils.SystemMessage exception, rst2pdf dies with a traceback instead of a nicer error message.

I've checked that this is still happening in master.

```
$ ./env/bin/rst2pdf fail.rst 
fail.rst:15: (SEVERE/4) Title level inconsistent:

::
..
Traceback (most recent call last):
  File "./env/bin/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf==0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/home/valhalla/tmp/rst2pdf/env/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/home/valhalla/tmp/rst2pdf/env/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 540, in createPdf
    settings_overrides=settings_overrides)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 479, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2962, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    if self.check_subsection(source, style, lineno):
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 356, in check_subsection
    self.parent += self.title_inconsistent(source, lineno)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 374, in title_inconsistent
    line=lineno)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: fail.rst:15: (SEVERE/4) Title level inconsistent:

::
..
```

Compare it with the output of the rst2\* tools from docutils:

```
$ rst2html fail.rst 
fail.rst:15: (SEVERE/4) Title level inconsistent:

::
..
Exiting due to level-4 (SEVERE) system message.
```

Where `fail.rst` is the minimal example from the link above:

```
========
testing
========

big heading
===========

heading
-------
text here

big heading
===========

::
..
    a set of text for testing
```

**Comment by ralsina** [comment] 2018-11-08 10:56
Yes, confirmed.

**Comment by lornajane** [comment] 2021-08-08 17:07
Closing since I think we have this covered by #990

**Closed by lornajane** 2021-08-08 17:07 UTC
Labels: bug
