### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by flying-sheep** [rst2pdf/rst2pdf#537] opened 2015-07-03 17:36 UTC

**Comment by pmaupin** [comment] 2015-07-03 17:55
So, I haven't really been following along all that well, but at least one person is working on this.  He didn't fork it from Roberto, so it doesn't show up in the graph.  I only know about it because he filed an issue against pdfrw.  Anyway, it's here:

https://github.com/aquavitae/rst2pdf

FWIW, many of the pieces are in place.  reportlab, docutils, pdfrw all support Python 3.  Based on my experience porting pdfrw, I have a few observations:

1) If we limit to 2.6, 2.7, 3.3, 3.4, I don't think it will be all that hard.

2) reportlab keeps changing output and even the setting to ask it not to do that doesn't help.  (To be fair, this may partly be my fault in my pdfrw tests, because I don't think I was ordering dictionaries before wrapping them in reportlab objects).

3) The idea of using MD5 checksums for the tests is still viable, but the right answer may involve round-tripping the reportlab output back through pdfrw and then spitting it back out, because you can probably do that in such a way that the metadata gets stripped and everything else gets placed in a reproducible order.

Thanks,
Pat

**Comment by flying-sheep** [comment] 2015-07-03 18:21
promising! since this module’s author hasn’t been active for 2 years here, @ralsina should at least add him as collaborator and prepare a release using his work.

**Comment by ralsina** [comment] 2015-07-03 18:23
@pmaupin has graciously offered to start an organization so we can migrate rst2pdf to a "neutral" place, and then this can move forward.

**Comment by pmaupin** [comment] 2015-07-03 18:42
Actually, there's not much to creating the organization.  You should already have an invite, Roberto.  Once you accept it, I can either fork the repo and manually (well, there seem to be some scripts available to do it) copy the issues over, or you could transfer ownership of the repo (and then clone it back if you want) so that the issues automatically move over.

Transferring is easy -- I transferred the astor repository to berkerpeksag when I wasn't interested in it.  You just go to the repo, click on the screwdriver/wrench icon  on the lower-right, and then scroll down and press the transfer button.

**Comment by ralsina** [comment] 2015-07-03 18:47
Done.

**Comment by flying-sheep** [comment] 2015-07-06 09:16
cool!

so what’s left before merging @aquavitae’s work?

**Comment by pmaupin** [comment] 2015-07-06 14:24
Well, for one thing, you could just go and use his work now :)

In terms of merging it into master (and then later doing a release), I have had a private conversation with him and I think we agree that the right answer is going to be to treat what he has done as an advance-development branch, and to move a bit more slowly.

The real problem is the tests.  Roberto had collect a zillion functional tests over the years, but they had to be run semi-manually.  When I started to contribute, I wrote a test runner that would compute and compare MD5 checksums from the outputs of the tests.  It was a great idea -- except for the fact that underlying libraries (mainly reportlab) keep making changes that make changes in the output.  Some of those changes are not functional; but others affect the image or links of the output PDFs.  Either way, somebody has to go figure out what changed and why and maybe make a workaround.

I should have been paying more attention after that, because I have a bit of technology in my pdfrw package for rewriting PDFs to make them more canonical.  But I wasn't paying attention because things were working great for me, and I now see the problem, and I see that Roberto did a valiant job keeping up with reportlab changes, but eventually, I think, he had enough, and had more interesting things to work on, and all the old versions of stuff were still around, and it worked great for him, and why the heck would anybody keep beating his head against the wall like that, anyway?

Anyway, if the tests were difficult to keep up with for someone like Roberto, who started doing it manually, you can imagine they were practically impossible for someone coming in fresh.  aquavitae is a firm believer in tests.  Strategically, he wants to move from pure functional tests to more reliance on unit tests, which is more work in a different area but would, as he points out, help to isolate rst2pdf testing a bit from other packages.  Nonetheless, functional testing will always be integral to the strategy, because people aren't using rst2pdf without reportlab, so when (not if, noooo) a reportlab change breaks things, we need to know and create a workaround.  aquavitae realizes this too -- in fact he has integrated technology into the automated tests on his branch that will do a pixel-by-pixel comparison.  That's great for the visuals, but we still need an automated way to make sure, for example, that links didn't break.

So, when aquavitae started playing with rst2pdf, he found that, for him, the tests didn't do anything useful at all.  I think I may know why -- for some reason with a fairly recent version of buildout, I was having issues with the development build grabbing system libraries, because the lib/dist-packages was added to the system path (because some library in there was OK to use) *ahead* of the reportlab library, so it was picking up the 3.2 system reportlab instead of the 2.5 in the development package, and those are **completely** different.

So from his perspective, he had no working tests, a moribund project, some issues he wanted to solve and features he wanted to add, and other stuff he didn't really care that much about.  (FWIW, I think he started this in July of last year.)

His code may work perfectly -- I don't know because I haven't even gotten as far as trying it yet.  My own purely tactical task right now is resuscitating the original tests and updating the test runner to be a bit less sensitive to reportlab changes, because there was a lot of work put into those tests.  I have 206 of them comparing correctly; perhaps @ralsina can let me know if that is reasonable.

Strategically, we need to come up with a document that explains what we are doing moving forward, so we are all on the same page.  aquavitae and I have communicated about this, but we are both pretty busy right now.  Expect to see some movement later this month, and I would not be surprised if we were ready for a release in 3 months.  With more help, we might be able to shave some time off that :)

But again, it is my understanding that the work that he has done will, in fact, work for some documents.  Just bear in mind if you use it that reportlab keeps changing things, and historically we have worked hard to mitigate the results of those changes so that things don't change that much from release to release of rst2pdf, so a document built with that branch may not be visually identical to one built from the next release.

Thanks,
Pat

**Comment by aquavitae** [comment] 2015-07-09 09:25
Just to chip in, my branch works for about 80% of cases, so chances are it will work now for you.  A couple of things I know are not working:

* Math
* Anything involving wordaxe
* Some graphics seem to have minor sizing issues

**Comment by ralsina** [comment] 2015-07-09 12:17
@aquavitae wordaxe is (AFAIK) quite abandoned. It's also a very non-trivial piece of code, although I have touched the innards a few times.

In any case, if it can be made to work, I think one of the main things rst2pdf needs is to be less flexible (like, the N alternative ways to embed images have to go and keep just Pillow + SVG via inkscape as an alternative because it works much better), and one of those cases, I think, is wordaxe.

If it can work reliably, it should be a fixed dependency and used, otherwise just kill the support.

**Comment by flying-sheep** [comment] 2015-07-09 13:42
there are [more](https://www.google.de/search?q=python+hyphenation+texlib) hyphenation libraries.

and as said, it would be awesome if we could use [texlib](https://github.com/akuchling/texlib) in the long run. maybe there’s a way to combine those.

**Comment by ralsina** [comment] 2015-07-09 13:51
It's not just hyphenation, it's hyphenation and layout as a platypus paragraph object. I have no idea what exists, but as many as they may be, just pick one :-)

**Comment by pmaupin** [comment] 2015-07-09 15:21
I hadn't tried to run the tests in forever until last week, and it took me a long time to get to checksums that matched the good ones Roberto had logged.  I noticed that when I installed wordaxe, most of the tests failed, because of the changed checksums.

To me, this says that even if we keep the ability to use wordaxe, the code shouldn't dynamically start using it simply because it is installed.

I think we should make a lot more use of extensions.  We could have an extension that pipes text through somebody's favorite hyphenator/layout, and people could reuse or extend that.  We also need to clearly explain that extensions don't have to be inside the extensions directory, and encourage people to do their own customizations, and to contribute extensions.

So, when we remove wordaxe from the main code, we should make sure the hooks for it stay put (maybe by porting it to an optional extension as an example).

Also, if somebody contributes or cares about an extension, then we can sign them up as a maintainer for it, and if they don't keep up on maintaining the tests, we'll ignore the test results for that extension and list it as unmaintained.  I think it's the only way the overall project maintainers will be able to stay sane.

I think this is how we might want to handle image processing, as well.  Yes, pick a default, but allow easy override with a new extension, because none of the image readers works perfectly on every image.

On that note, I was just looking at the new-ish (2012) html stuff in utils, and I think we should move that to an extension, especially since it tries to import the world (thereby slowing down rst2pdf for everybody not using it).

So my bottom line is that we should simplify the main code (which simplifies the testing strategy a bit), but work to make it even easier to add one-off support (either tested or untested) for stuff.

I think (and hope) that the move to github will greatly facilitate this.  Pull requests are awesome conversation starters, and if somebody contributed something like the HTML support today, we should have the discipline to say "That's a great idea, but not everybody will want to use it, and it will change the results on half the tests.  It would be perfect for an extension -- would you like some help getting it into one?"

**Comment by aquavitae** [comment] 2015-07-10 05:30
@ralsina I fully agree about fixing the depende

@pmaupin

**Comment by pmaupin** [comment] 2015-07-10 17:04
@aquavitae 

(Re)organization of the extensions is certainly something we could do, but it seems to me (especially if we push things like images out to extensions) that we will certainly want to have some base extensions in with the main package, both for out-of-the-box functionality that is easy to override, and for examples.

I just had a quick look at yapsy.  I can see how it buys discovery (e.g. if you want to list out all the extensions), but I don't particularly like the default of having a separate file (in addition to the Python) for each extension.  It looks like you can override that with the PluginFileAnalyzerMathingRegex [sic], but maybe if you do it that way you won't have as much info per extension.

So, I guess I'm slightly biased -- probably for at least 4 reasons:

- I wrote the current extension system.  It's an ugly baby, sure, but it's pretty simple, easy to understand, and re-uses the built-in Python module import mechanism for extension location.  (It doesn't do available extension discovery, but that doesn't seem like a hard problem.)  And, yeah, we need to develop canonical procedures for how we manage the plugins, but I think that is true even if you use a system like yapsy, although those systems have the benefit of helping to guide you a little bit, maybe.

- IUsedToWorkWithAGuyWhoThoughtEveryVariableShouldTellItsOwnStory and his spelling wasn't very good, and I just had a 3-decade-old flashback of grepping for something very similar to PluginFileAnalyzerMathingRegex and not being able to find the damn thing because I just glanced at the name on the screen and misspelled it on the grep.  This visceral reaction may be a silly, non-logical reason for not wanting to yapsy, but there it is -- the package is rife with misspellings, and part of me wishes for a cleanup, and part of me cringes at the thought of how much stuff that would break.

- I don't like multiple files per extension.  Yapsy would make more sense if it had a canonical way for the Python plugin to identify things like which package it wanted to plug-in to, what services it provides, etc., all discoverable after import.  (Maybe that's there somewhere; it wouldn't be too hard to add, but the fact that the initial cut of it uses two files indicates to me that the starting underlying philosophy is possibly not one I agree with.)

- I would like us to consider moving away from automatically enabling features just because we can -- especially features with multiple possible providers.  I think part of the reason that rst2pdf got away from us was the laissez-faire approach to using stuff if it is available.  It's a cool approach that can do a lot of wonderful things for a lot of people, but the emergent behavior it fosters is completely irreproducible and untestable.  So, if I'm mean enough to think that the user should specify whether he wants to use wordaxe or not (either on the command line or in a config file),  this means that I'm probably not really interested in a lot of the cool stuff that yapsy could enable.

One other thing I will mention.  The image stuff is complicated enough (package A won't read image X correctly; package B won't read image Y correctly; I want to use both image X and Y in my PDF) that, in addition to command line and config files, I think we need the ability, e.g. through the class or raw directive, to dynamically load and even unload extensions (so that each image can be processed properly).  Obviously, that capability would be generic, so could be used with things like wordaxe (or whatever the hyphenator-du-jour is).  If you have a document you want wordaxe used on, you could spell it out in a raw or class declaration inside the document.  If you only want wordaxe used on a single paragraph, disable it after the paragraph.  If you want wordaxe used all the time, put it in your config file.


OK, having said all that, I really did only look at yapsy for a short period of time just now, and I would definitely be interested in seeing what @ralsina has to say about it, because he has used both the rst2pdf extension mechanism and yapsy fairly extensively, I think (and apparently even contributed to yapsy and wrote some doc on it).

I the main question is this: if you separate out yapsy-the-package from any goodness in yapsy-the-methodology that we might want (which could be perhaps be taught and propagated separate from yapsy-the-package) then, in the specific case of rst2pdf, is it worth it to have yapsy-the-package as a dependency?

**Comment by ralsina** [comment] 2015-07-10 17:08
On 10/07/15 14:04, Patrick Maupin wrote:
> OK, having said all that, I really did only look at yapsy for a short 
> period of time just now, and I would definitely be interested in 
> seeing what @ralsina <https://github.com/ralsina> has to say about it, 
> because he has used both the rst2pdf extension mechanism and yapsy 
> fairly extensively, I think (and apparently even contributed to yapsy 
> and wrote some doc on it).

Yapsy is ok. Once it's working it staysout of the way.

And you can do things like this: http://plugins.getnikola.com :-)

There is also setuptools plugins which may be handy.

**Comment by pmaupin** [comment] 2015-07-10 17:58
That's a lot of plugins you have there!

(And in reviewing them, it's clear that the piece I wasn't thinking about was help for the installation of plugin dependencies -- that's useful.)

**Comment by ralsina** [comment] 2015-07-11 00:06
Indeed! At one point Nikola's core was pretty full, so we shed a bunch of them to the "store". And now we go the other way around: plugins start there and if they rock they get pulled in.

**Comment by valholl** [comment] 2016-06-23 14:46
Are there any news on this? With 2020 getting closer it would be nice to reduce one's dependency on python2.

(btw, for one of the souces of non-reproducibility in the output there is #525, which may or may not help)

**Comment by akrabat** [comment] 2019-02-12 10:33
Closing as superseded by #742

**Closed by akrabat** 2019-02-12 10:33 UTC
Labels: discussion
