### ISSUE TITLE
PDF is corrupt when Table of Contents is longer than one page

### ISSUE THREAD

**Issue by reteptilian** [rst2pdf/rst2pdf#548] opened 2015-08-20 22:43 UTC
Since updating to 0.93 we can no longer generate valid PDFs.  I made a testcase and found that if I had a doc with enough sections so that the TOC did not fit on a single page, the generated PDF was bad.  As soon as I deleted enough sections so that it fit on one page, the PDF was good again.

The Adobe Acrobat error that is displayed is "There was a problem reading this document (14)."

**Comment by sarnold** [comment] 2016-01-30 02:06
I can't reproduce this - we have a small svg patch on docutils (recent git snapshot https://github.com/VCTLabs/docutils.git ) and rst2pdf-0.93-r2 (gentoo package with small logging patch).  We've been making large documents (eg, interface specs) and I just made a slide outline (with .. contents::) and it works fine (see https://github.com/VCTLabs/elc2016-presentations for the slides).  What's missing from this picture?  Is this fixed?  Seems unlikely to be a side-effect of the patch, but stranger things have happened...

**Comment by fgerstenberg** [comment] 2016-04-06 07:48
I ran across the same issue when using the rst2pdf extension for Sphinx to produce a software documentation. The project builds fine until the TOC reaches a length that can't fit on a single page, then the pdf output becomes unreadable, with the error mentioned by reteptilian.
Currently using Sphinx 1.31 and rst2pdf 0.93.dev_r0
I made a small example project. Building the pdf as it is produces unreadable output. Exchanging test_content_long with test_content_short in index.rst allows the TOC to fit in one page and pdf output is fine.
[rst2pdf_sphinx_test.zip](https://github.com/rst2pdf/rst2pdf/files/205956/rst2pdf_sphinx_test.zip)

**Comment by yyoyo** [comment] 2016-08-17 16:33
+1. 

When toc is longer than one page, I can't open the PDF document with Acrobat Reader on Windows.

I use rst2pdf 0.93.dev and sphinx 1.4.5.

Any news about this issue ?

**Comment by aknight1969** [comment] 2016-08-24 18:31
I am seeing the same problem with rst2pdf 0.93.dev-r0, and sphinx 1.4.6.

**Comment by aknight1969** [comment] 2016-08-26 20:08
I have done some additional research.

I was able to workaround the issue by back rev-ing reportlab to version 2.7

What revisions of reportlab are you using?  
I was using reportlab==3.3, when I uinitially saw the problem. However, I am able to reproduce the problem with reportlab==3.0.  RL 3.0 was a major upgrade, they state the apis have not changed, but the internals have. http://www.reportlab.com/documentation/relnotes/30/

**Comment by chrchr** [comment] 2016-12-12 19:07
Hi! I'm having this problem too, and I can confirm that it works with reportlab 2.7 and Pillow 2.1.0.

Here is my requirements.txt:

```
sphinx
reportlab==2.7
rst2pdf==0.93
Pillow==2.1.0
```

**Comment by jmones** [comment] 2018-05-10 14:09
I was hit by this issue too. I confirm that downgrading {{reportlab}}, {{rst2pdf}} and {{Pillow}} to the versions proposed by chrchr in https://github.com/rst2pdf/rst2pdf/issues/548#issuecomment-266521237 fixes the issue for me.

**Comment by lornajane** [comment] 2021-01-10 15:17
I know this has dragged on, but I was working on a similar issue with a long table and I can't replicate this bug today with:
```
Sphinx==1.8.5
reportlab==3.5.34
Pillow==7.1.0
```
I'm using the current master of rst2pdf (https://github.com/rst2pdf/rst2pdf/commit/f1d5efe17db0ee15ade0ed54c1f4520e4b7992ec1) and opening the file on Linux. I'll leave this open, can anyone confirm/deny this still exists?

**Comment by lornajane** [comment] 2023-12-06 19:52
I'm optimistically closing this reportlab-related bug as it doesn't seem to be a problem with the current tool versions. If you see it again, open a new issue and reference this one please.

**Closed by lornajane** 2023-12-06 19:52 UTC
Labels: bug, Priority-High, pending feedback
