### ISSUE TITLE
pip install rst2pdf==0.93 installs 0.93.dev

### ISSUE THREAD

**Issue by dvarrazzo** [rst2pdf/rst2pdf#532] opened 2015-05-01 18:55 UTC
Because of this, installation from a script always does something, even if rst2pdf is already installed.

```
$ virtualenv foo
New python executable in foo/bin/python
Installing setuptools, pip...done.

$ cd foo
$ source bin/activate
(foo)$ wget --quiet -O - "https://pypi.python.org/packages/source/r/rst2pdf/rst2pdf-0.93.tar.gz" | tar xzf -
(foo)$ cd ./rst2pdf-0.93/
(foo)$ python setup.py build install
...
Finished processing dependencies for rst2pdf==0.93.dev

(foo)$ rst2pdf --version
0.93.dev
```

**Comment by dvarrazzo** [comment] 2015-05-01 18:58
As you see from above, it doesn't seem pip fault: the same happens just with `python setup.py install`

**Comment by ralsina** [comment] 2018-11-08 13:42
Duplicate of #489

**Closed by ralsina** 2018-11-08 13:42 UTC
