### ISSUE TITLE
Non-anonymous hyperlink reference with embedded reference crashes rst2pdf

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#964] opened 2020-12-28 20:24 UTC
A hyperlink reference with another hyperlink reference embedded causes rst2pdf to crash if it isn't anonymous.

**Description of problem**

The following document creates a link with text "title" that points to the document's title, and it works as expected:

```
PDF Documents From Your Text Editor
###################################

See `title <PDF Documents From Your Text Editor_>`__ for more info.
```

Notice the `__` at the end of the link, denoting that it is an anonymous reference, that is, it wouldn't be possible later in the document to write `title_` and have it also point to the document's title.

Changing the double underscore to a single one, making it no longer anonymous:

```
PDF Documents From Your Text Editor
###################################

See `title <PDF Documents From Your Text Editor_>`_ for more info.
```

makes rst2pdf crash:

```
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 1683, in main
    RstToPdf(
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 562, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 254, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 230, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 207, in gather_elements
    return client.gather_elements(node, style=style)
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 374, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 254, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 230, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib/python3.9/site-packages/rst2pdf/genelements.py", line 186, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 287, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 270, in get_text
    return client.gather_pdftext(node)
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 365, in gather_pdftext
    return ''.join([self.gen_pdftext(n, replaceEnt) for n in node.children])
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 365, in <listcomp>
    return ''.join([self.gen_pdftext(n, replaceEnt) for n in node.children])
  File "/usr/lib/python3.9/site-packages/rst2pdf/basenodehandler.py", line 286, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/usr/lib/python3.9/site-packages/rst2pdf/genpdftext.py", line 252, in get_pre_post
    pre = u'<a name="%s"/>' % node['refuri']
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 625, in __getitem__
    return self.attributes[key]
KeyError: 'refuri'
```

This should be possible though, as there's a similar example in the docutils spec (though the link there ultimately points to an URL instead of a section):

https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases

🖥 **Versions**

`python -V`: 3.9.1

`pip freeze | grep rst2pdf`: 0.98

`pip freeze | grep reportlab`: 3.5.56

Which operating system are you using? Archlinux

**Comment by stephenfin** [comment] 2021-01-02 11:31
Duplicate of #820

**Closed by stephenfin** 2021-01-02 11:31 UTC
Labels: bug
