### ISSUE TITLE
twoColumn not defined

### ISSUE THREAD

**Issue by mwichmann** [rst2pdf/rst2pdf#1059] opened 2022-01-16 15:38 UTC
**Description of problem**
Sorry this isn't going to be a great issue report: since 0.99 dropped, our doc build fails with
```console
[ERROR] createpdf.py:1134 Template 'twoColumn' is not defined
```
createpdf isn't a direct dependency - it's pulled in by a moderately complex sphinx build.  I've changed sphinx versions without affecting it, rolling rst2pdt back to 0.98 lets it run to completion.

**What is the expected output? What do you see instead?**
Exepct the build to work :)

🖥 **Versions**

`python -V`: `Python 3.10.1`

`pip freeze | grep rst2pdf`:  `rst2pdf==0.99`

`pip freeze | grep reportlab`: `reportlab==3.6.5`

`pip freeze | grep Sphinx`: `Sphinx==4.3.2`

Which operating system are you using?
Linux (Fedora 35) - the dependency chain for this is in a virtualenv, not using Fedora-packaged versions.

**Additional information**

**Comment by akrabat** [comment] 2022-01-16 15:41
I thought that I had documented this in CHANGES, but it seems not. Sorry.

`twoColumn` isn't part of the default styles in 0.99. You need to add the `twocolumn` style file.

For stock rst2pdf, you'd use `-s twocolumn` and for Sphinx, I think it's `pdf_stylesheets = ['twocolumn']`

**Comment by mwichmann** [comment] 2022-01-16 15:51
Yeah, I can confirm adding the suggested Sphinx snip to the `conf.py` lets the build proceed.

Thanks!

**Comment by lornajane** [comment] 2022-05-01 16:59
I'll close this since it's now documented in `CHANGES`

**Closed by lornajane** 2022-05-01 16:59 UTC

**Comment by xjcl** [comment] 2023-02-08 13:33
This gets rid of the error message, but is not the behavior I want. I had a single-column PDF before, now if I write `pdf_stylesheets = ['sphinx', 'twocolumn']` for Sphinx's `conf.py`, it results in a two-column PDF. Is there any way to still have a single-column PDF?

**Comment by akrabat** [comment] 2023-02-08 13:38
> This gets rid of the error message, but is not the behavior I want. I had a single-column PDF before, now if I write `pdf_stylesheets = ['sphinx', 'twocolumn']` for Sphinx's `conf.py`, it results in a two-column PDF. Is there any way to still have a single-column PDF?

You can use:

```
.. PageBreak oneColumn
```

to start a new page that uses the `oneColumn` page template. This page template then stays in play until you change it again with another `.. PageBreak` directive.

**Comment by xjcl** [comment] 2023-02-08 13:57
I don't have any templates. I guess the problem is that `Sphinx` is applying `twoColumn` internally somewhere? (I updated `Sphinx` and `rst2pdf` simultaneously).

Although trying to install different combinations of packages I think neither package is responsible, but one of the third-party dependencies is. Sigh.

**Comment by xjcl** [comment] 2023-02-08 14:13
`Sphinx==3.5 rst2pdf==0.98` still has the desired behavior. Using `Sphinx==4.0 rst2pdf==0.98` does not work because it is not supported by that `rst2pdf` version, and the combination `Sphinx==3.5 rst2pdf==0.99` fails because of the `twoColumn` issue.

**Comment by xjcl** [comment] 2023-02-09 01:19
I solved it now by just specifying `pdf_stylesheets = ['twocolumn', 'sphinx']` (flipping the arguments, duh!).

Note that I DID try `pdf_stylesheets = ['sphinx', 'twocolumn', 'onecolumn']` and `pdf_stylesheets = ['sphinx', 'onecolumn', 'twocolumn']` prior to posting this question, both of which kept giving me a two-column PDF. It seems weird to me anyway that I need to specify the `'twocolumn'` template at all if I don't actually want to use it in my PDF? I'm also surprised the second argument in the list takes appears to take precedence over the first one, but oh well.

Thanks again for your work on the project and your quick answer earlier.
