### ISSUE TITLE
problem with rst2pdf version (0.93 v 0.93.dev) breaks pip freeze/install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#489] opened 2015-03-12 16:37 UTC
```
Here are steps to reproduce:

❤ virtualenv --no-site-packages tmp/rst2pdf
The --no-site-packages flag is deprecated; it is now the default behavior.
New python executable in tmp/rst2pdf/bin/python
Installing 
distribute......................................................................
................................................................................
.......................................done.
Installing pip...............done.

❤ source tmp/rst2pdf/bin/activate

❤ pip install rst2pdf
[...]

Thank you!
❤ pip freeze > requirements.txt

❤ rm -rf tmp/rst2pdf/

❤ virtualenv --no-site-packages tmp/rst2pdf
The --no-site-packages flag is deprecated; it is now the default behavior.
New python executable in tmp/rst2pdf/bin/python
Installing 
distribute......................................................................
................................................................................
.......................................done.
Installing pip...............done.

❤ source tmp/rst2pdf/bin/activate

❤ pip install -r requirements.txt 
[...]
Downloading/unpacking rst2pdf==0.93.dev (from -r requirements.txt (line 7))
  Could not find a version that satisfies the requirement rst2pdf==0.93.dev (from -r requirements.txt (line 7)) (from versions: )
No distributions matching the version for rst2pdf==0.93.dev (from -r 
requirements.txt (line 7))
Storing complete log in /home/egh/.pip/pip.log

```

Original issue reported on code.google.com by `ehetzner@gmail.com` on 10 Jan 2013 at 4:21

**Comment by ralsina** [comment] 2018-11-07 14:10
Confirmed. Looks like we have a mismatch between what the release is marked as in PyPI and what is inside the package itself.

Should be fixed if rst2pdf ever does a new release.

**Comment by akrabat** [comment] 2018-11-07 14:13
> Should be fixed if rst2pdf ever does a new release. 

We're getting close now. I'm hopeful that it'll happen before the end of 2018.

**Comment by ralsina** [comment] 2018-11-07 14:30
Weeee! Awesome :-)

**Comment by lornajane** [comment] 2020-05-21 16:57
New releases have occurred so I believe this to be fixed.

**Closed by lornajane** 2020-05-21 16:57 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated

**Comment by imphil** [comment] 2020-12-01 16:11
A heads up for everyone stumbling across this issue today because they get `ERROR: Requested rst2pdf from https://files.pythonhosted.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz#sha256=3af44283ced19030a8286e8f8d71106ca6c78efe4bc95e9af42d678c363efcbc has different version in metadata: '0.93.dev0'` errors.

* You're most likely running Python 3.5 (e.g. on Ubuntu 16.04)
* You're running pip >= 20.3
* The solution is to upgrade to Python 3.6, force pip to use the old dependency resolver, or downgrade pip.

Long explanation: 
* rst2pdf 0.93 is the last version to support Python 3.5. rst2pdf 0.93 also has a packaging error (as discussed in this issue).
* pip has enabled a new dependency resolver by default in version 20.3, which rolled out today-ish. 
* The new dependency resolver flags the packaging error in rst2pdf as fatal, where the old resolver did silently ignore the problem. (See also https://github.com/pypa/pip/issues/8745.)
* This makes rst2pdf 0.93 uninstallable with the new resolver; since this version is also the last version to support Python 3.5, pip errors out.

**Comment by stephenfin** [comment] 2020-12-02 12:07
I wonder can we remove this package from PyPI? Is that wise?

**Comment by imphil** [comment] 2020-12-02 12:28
If you remove 0.93 the resolver will pick up an earlier version (which don't have version information, so it looks like they are compatible with Python 3.5). If you want to resolve this problem for all users then I'd recommend doing a 0.93.1 release which only fixes the packaging.

**Comment by stephenfin** [comment] 2020-12-02 15:05
> If you remove 0.93 the resolver will pick up an earlier version (which don't have Python requirement information, so it looks like they are compatible with Python 3.5). If you want to resolve this problem for all users then I'd recommend doing a 0.93.1 release which only fixes the packaging.

I don't believe any releases prior to [0.95](https://pypi.org/project/rst2pdf/0.95/) is compatible with Python 3, so perhaps the wiser solution would be to release a 0.95.1 that re-adds support for Python 3.5, rather than a 0.93.1 that we know doesn't work. Will continue this discussion in #955.
