### ISSUE TITLE
Rst2pdf fails with "double target"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#524] opened 2015-03-12 16:37 UTC
```
What steps will reproduce the problem?
1. Create this .rst file:

Click on `some link <foo_>`_

.. _foo: http://google.com

2. rst2pdf <file>
3. IndexError

What is the expected output? What do you see instead?

I expect rst2pdf to generate a file with a link to google.com called "some link"

Please answer the following questions, they are *very* important:

* Version of rst2pdf?

0.93.dev0

* Version of reportlab?
3.1.8-1
* Are you using wordaxe, and if true, what version?
1.0.1-5
* Are you using rst2pdf with Sphinx, and if true, what version?
no
Please provide any additional information below.

Attached patch fixes it.

```

Original issue reported on code.google.com by `fdev31@gmail.com` on 6 Feb 2015 at 8:18

Attachments:
- [rst2pdf.patch](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-524/comment-0/rst2pdf.patch)

**Comment by ralsina** [comment] 2018-11-07 19:55
Duplicate of Issue #569

**Closed by ralsina** 2018-11-07 19:55 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
